custom:
#  default_url: {import: snippets/url.txt}
#  proxy_subscription=SYSTEM


  enable_rule_generator: true
  overwrite_original_rules: true

  proxy_groups:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/groups.txt}

  rulesets:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/rulesets_cdn.txt}

#  clash_rule_base: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/base/all_base.tpl
#  clash_rule_base: https://raw.githubusercontent.com/Dashboard2/subpref/master/base/all_base2.tpl
#  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf

  rename_node:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/rename_node.txt}

  add_emoji: true
  remove_old_emoji: true
  emojis:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/emoji.txt}

#  include_remarks: []
#  exclude_remarks: []

  template_args:
  - {key: clash.http_port, value: 7890}
  - {key: clash.socks_port, value: 7891}
  - {key: clash.mixed_port, value: 7891}
  - {key: clash.redir_port, value: 7892}
  - {key: clash.allow_lan, value: true}
  - {key: clash.log_level, value: info}
