custom:
  enable_rule_generator: true
  overwrite_original_rules: true

  proxy_groups:
  - {import: https://raw.githubusercontent.com/Dashboard2/scc/master/snippets/groups.txt}

  rulesets:
  - {import: https://raw.githubusercontent.com/Dashboard2/scc/master/snippets/rulesets_cdn.txt}

#  clash_rule_base: base/forcerule.yml
#  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf

  rename_node:
  - {import: https://raw.githubusercontent.com/Dashboard2/scc/master/snippets/rename_node.txt}

  add_emoji: true
  remove_old_emoji: true
  emojis:
  - {import: https://raw.githubusercontent.com/Dashboard2/scc/master/snippets/emoji.txt}

#  include_remarks: []
  exclude_remarks: ["(切换.*订阅|到期|剩余流量|时间|官网|产品)"]
#  template_args:
#  - {key: clash.dns.port, value: 5353}
