custom:
  default_url: {import: snippets/url.txt}

  enable_rule_generator: false
  overwrite_original_rules: false

  custom_proxy_group:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/groups.txt}

  rulesets:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/rulesets_cdn.txt}

  clash_rule_base: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/base/all_base.tpl
#  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf

  rename_node:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/rename_node.txt}

  add_emoji: true
  remove_old_emoji: true
  rules:
  - {import: https://cdn.jsdelivr.net/gh/Dashboard2/subpref@master/snippets/emoji.txt}

  globals:
  - {key: clash.http_port, value: 7890}
  - {key: clash.socks_port, value: 7891}
  - {key: clash.mixed_port, value: 7891}
  - {key: clash.redir_port, value: 7892}
  - {key: clash.allow_lan, value: true}
  - {key: clash.log_level, value: info}
